name: fhir_r4_path
description: Dart Library supporting (almost) all Functionality for FHIRPath.
version: 0.4.4
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r4

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.0
  fhir_r4: ^0.4.3
  # fhir_r4:
  #   path: ../fhir_r4
  http: ^1.6.0
  ucum: ^0.6.0
  universal_io: ^2.2.2

dev_dependencies:
  test: ^1.27.0
 