name: fhirr4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dependency_overrides:
  fhir_r4:
    path: packages/fhir_r4
  fhir_r4_at_rest:
    path: packages/fhir_r4_at_rest
  fhir_r4_path:
    path: packages/fhir_r4_path

dev_dependencies:
  melos: ^7.3.0
  very_good_analysis: ^10.0.0
