name: fhir_r4_at_rest
description: A Dart package providing type-safe, fluent RESTful operations for FHIR R4 resources. 
version: 0.4.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r4

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  fhir_r4: ^0.4.3
  # fhir_r4:
  #   path: ../fhir_r4
  http: ^1.3.0

dev_dependencies:
  test: ^1.27.0
